"""empty message

Revision ID: 233538540202
Revises: 236711d12b08
Create Date: 2023-12-11 14:13:37.812353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233538540202'
down_revision = '236711d12b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_compras')
    # ### end Alembic commands ###
