"""empty message

Revision ID: 236711d12b08
Revises: 15ca67e6bc54
Create Date: 2023-11-29 19:23:40.810549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236711d12b08'
down_revision = '15ca67e6bc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_username_key', ['username'])

    # ### end Alembic commands ###
