"""empty message

Revision ID: 34be48e93055
Revises: ed94a3d52723
Create Date: 2023-11-27 14:55:04.680471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34be48e93055'
down_revision = 'ed94a3d52723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('orden_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'ordenes', ['orden_id'], ['id'])

    with op.batch_alter_table('facturas_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'facturas', ['factura_id'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('ordenes_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])
        batch_op.create_foreign_key(None, 'ordenes', ['orden_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unitFormat', sa.String(length=120), nullable=False))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('profiles_facebook_key', type_='unique')
        batch_op.drop_constraint('profiles_twitter_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('profiles_twitter_key', ['twitter'])
        batch_op.create_unique_constraint('profiles_facebook_key', ['facebook'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('unitFormat')

    with op.batch_alter_table('ordenes_productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producto_id')
        batch_op.drop_column('orden_id')

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('facturas_productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producto_id')
        batch_op.drop_column('factura_id')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('orden_id')
        batch_op.drop_column('user_id')

    op.drop_table('favoritos')
    # ### end Alembic commands ###
