"""empty message

Revision ID: 5487c7fe1343
Revises: 08dfd04d89d6
Create Date: 2023-11-23 21:33:54.290543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5487c7fe1343'
down_revision = '08dfd04d89d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('favoritos', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['lastName'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('favoritos')
        batch_op.drop_column('lastName')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
