"""empty message

Revision ID: 7d0da0317553
Revises: f729e60541aa
Create Date: 2023-11-24 13:39:46.617460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0da0317553'
down_revision = 'f729e60541aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.drop_constraint('Producto_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Producto_users_id_fkey', 'users', ['users_id'], ['id'])

    # ### end Alembic commands ###
