"""empty message

Revision ID: 950836d2b776
Revises: 95e30a688e2d
Create Date: 2023-11-24 13:20:44.524327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950836d2b776'
down_revision = '95e30a688e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carrito', schema=None) as batch_op:
        batch_op.drop_column('precio')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
