"""empty message

Revision ID: f729e60541aa
Revises: cb4a56cbaf6d
Create Date: 2023-11-24 13:37:53.854105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f729e60541aa'
down_revision = 'cb4a56cbaf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Producto', ['producto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carrito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###
